### ISSUE TITLE
Unable to deploy ops-manager in GKE 1.16.8-gke.15

### ISSUE THREAD

**Issue by nithinkanil** [mongodb/mongodb-enterprise-kubernetes#104]
I tried to deploy the ops manager in GKE. I am getting the below mentioned error. 

```
[Starting Logging - App Version: 4.2.12.56844.20200408T2127Z]
2020-06-05T03:15:58.040+0000 [main] WARN  com.xgen.svc.core.AppSettings [AppSettings.java.run:510] - Failed to refresh database properties
com.mongodb.MongoTimeoutException: Timed out after 20000 ms while waiting for a server that matches com.mongodb.Mongo$4@47ec7422. Client view of cluster state is {type=REPLICA_SET, servers=[{address=ops-manager-db-1.ops-manager-db-svc.mongodb.svc.mycompany.net:27017, type=UNKNOWN, state=CONNECTING}, {address=ops-manager-db-2.ops-manager-db-svc.mongodb.svc.mycompany.net:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: connect timed out}}, {address=ops-manager-db-0.ops-manager-db-svc.mongodb.svc.mycompany.net:27017, type=UNKNOWN, state=CONNECTING}]
        at com.mongodb.connection.BaseCluster.createTimeoutException(BaseCluster.java:389)
        at com.mongodb.connection.BaseCluster.selectServer(BaseCluster.java:108)
        at com.mongodb.Mongo.getConnectedClusterDescription(Mongo.java:887)
        at com.mongodb.Mongo.createClientSession(Mongo.java:877)
        at com.mongodb.Mongo$3.getClientSession(Mongo.java:866)
        at com.mongodb.Mongo$3.execute(Mongo.java:823)
        at com.mongodb.Mongo$3.execute(Mongo.java:813)
        at com.mongodb.DBCursor.initializeCursor(DBCursor.java:877)
        at com.mongodb.DBCursor.hasNext(DBCursor.java:144)
        at com.xgen.svc.core.dao.system.AppPropertyDao.getValues(AppPropertyDao.java:41)
        at com.xgen.svc.core.AppSettings.getDBProperties(AppSettings.java:527)
        at com.xgen.svc.core.AppSettings$DatabasePropertiesRefresher.run(AppSettings.java:502)
        at com.xgen.svc.core.AppSettings.refreshDatabaseCache(AppSettings.java:757)
        at com.xgen.svc.core.AppSettings.<init>(AppSettings.java:295)
        at com.xgen.svc.core.AppSettings.<init>(AppSettings.java:228)
        at com.xgen.svc.core.PreFlightCheck$1.configure(PreFlightCheck.java:245)
        at com.google.inject.AbstractModule.configure(AbstractModule.java:61)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:344)
        at com.google.inject.spi.Elements.getElements(Elements.java:103)
        at com.mycila.inject.jsr250.Jsr250.hasJSR250Module(Jsr250.java:85)
        at com.mycila.inject.jsr250.Jsr250.createInjector(Jsr250.java:73)
        at com.mycila.inject.jsr250.Jsr250.createInjector(Jsr250.java:47)
        at com.mycila.inject.jsr250.Jsr250.createInjector(Jsr250.java:43)
        at com.xgen.svc.core.PreFlightCheck.<init>(PreFlightCheck.java:89)
        at com.xgen.svc.mms.MmsPreFlightCheck.<init>(MmsPreFlightCheck.java:68)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at com.xgen.svc.core.PreFlightCheck.main(PreFlightCheck.java:205)
2020-06-05T03:16:18.170+0000 [main] WARN  com.xgen.svc.core.AppSettings [AppSettings.java.run:510] - Failed to refresh database properties
com.mongodb.MongoTimeoutException: Timed out after 20000 ms while waiting for a server that matches com.mongodb.Mongo$4@2264e43c. Client view of cluster state is {type=REPLICA_SET, servers=[{address=ops-manager-db-1.ops-manager-db-svc.mongodb.svc.mycompany.net:27017, type=UNKNOWN, state=CONNECTING}, {address=ops-manager-db-2.ops-manager-db-svc.mongodb.svc.mycompany.net:27017, type=UNKNOWN, state=CONNECTING}, {address=ops-manager-db-0.ops-manager-db-svc.mongodb.svc.mycompany.net:27017, type=UNKNOWN, state=CONNECTING}]
        at com.mongodb.connection.BaseCluster.createTimeoutException(BaseCluster.java:389)
        at com.mongodb.connection.BaseCluster.selectServer(BaseCluster.java:108)
        at com.mongodb.Mongo.getConnectedClusterDescription(Mongo.java:887)
        at com.mongodb.Mongo.createClientSession(Mongo.java:877)
        at com.mongodb.Mongo$3.getClientSession(Mongo.java:866)
        at com.mongodb.Mongo$3.execute(Mongo.java:823)
        at com.mongodb.Mongo$3.execute(Mongo.java:813)
        at com.mongodb.DBCursor.initializeCursor(DBCursor.java:877)
        at com.mongodb.DBCursor.hasNext(DBCursor.java:144)
        at com.xgen.svc.core.dao.system.AppPropertyDao.getValues(AppPropertyDao.java:41)
        at com.xgen.svc.core.AppSettings.getDBProperties(AppSettings.java:527)
        at com.xgen.svc.core.AppSettings$DatabasePropertiesRefresher.run(AppSettings.java:502)
        at com.xgen.svc.core.AppSettings.refreshDatabaseCache(AppSettings.java:757)
        at com.xgen.svc.core.AppSettings.<init>(AppSettings.java:295)
        at com.xgen.svc.core.AppSettings.<init>(AppSettings.java:228)
        at com.xgen.svc.core.PreFlightCheck$1.configure(PreFlightCheck.java:245)
        at com.google.inject.AbstractModule.configure(AbstractModule.java:61)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:344)
        at com.google.inject.spi.Elements.getElements(Elements.java:103)
        at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:137)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at com.mycila.inject.jsr250.Jsr250.createInjector(Jsr250.java:73)
        at com.mycila.inject.jsr250.Jsr250.createInjector(Jsr250.java:47)
        at com.mycila.inject.jsr250.Jsr250.createInjector(Jsr250.java:43)
        at com.xgen.svc.core.PreFlightCheck.<init>(PreFlightCheck.java:89)
        at com.xgen.svc.mms.MmsPreFlightCheck.<init>(MmsPreFlightCheck.java:68)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at com.xgen.svc.core.PreFlightCheck.main(PreFlightCheck.java:205)
```
I am using the following ops manager configuration

```
apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: ops-manager
spec:
  # the number of Ops Manager instances to run. Set to value bigger
  # than 1 to get high availability and upgrades without downtime
  replicas: 1

  # the version of Ops Manager distro to use
  version: 4.2.12

  # optional. Specify the custom cluster domain of the Kubernetes cluster if it's different from the default one ('cluster.local').
  # This affects the urls generated by the Operator.
  # This field is also used for Application Database url
  clusterDomain: mycompany.net

  # the name of the secret containing admin user credentials.
  # Either remove the secret or change the password using Ops Manager UI after the Ops Manager
  # resource is created!
  adminCredentials: ops-manager-admin-secret

  # optional. The Ops Manager configuration. All the values must be of type string
  configuration:
    mms.fromEmailAddr: "admin@thecompany.com"

  # the application database backing Ops Manager. Replica Set is the only supported type
  # Application database has the SCRAM-SHA authentication mode always enabled
  applicationDatabase:
    members: 3
    # optional. Configures the version of MongoDB used as an application database.
    # The bundled MongoDB binary will be used if omitted and no download from the Internet will happen
    version: 4.2.6-ent
    persistent: true
    podSpec:
      cpu: '0.25'

```
I didn't see any error in mongodb enterprise operator.

**Comment by rodrigovalin** [comment]
Hello @nithinkanil,

It seems that Ops Manager is trying to access the backing database (usually called appdb) but it is unable to connect to it. I presume your `clusterDomain` is **not** `mycompany.net`, and that might be the source of the problem.

Remove or comment the  from the  `clusterDomain: mycompany.net` line from the Ops Manager Custom Resource and apply the changes, or set the correct `clusterDomain` if yours is not the default `cluster.local`.

After applying this change the operator should be able to correct the configuration as needed and Ops Manager should be able to start.

If this does not solve the case, please give me the output of the following commands:

* `kubectl get opsmanagers -o yaml`
* `kubectl get pods`
* `kubectl get services`

Thanks!

**Comment by nithinkanil** [comment]
@rodrigovalin Thanks, It worked. Commented the company domain info.
