### ISSUE TITLE
Odd error on OpenShift 4.5 with the operator pod.   Restarted cluster and operator pod won't startup.  Had to delete all MongoDB instances.

### ISSUE THREAD

**Issue by alberttwong** [mongodb/mongodb-enterprise-kubernetes#160]
I didn't know how to fix this.   Shutdown and restarted my cluster.   Operator pod was in crash loop.  Pulled the logs and tried to fix it.   I deleted the operator and reinstalled it and still had the issue.   I had delete all my mongoDB instances and then delete the operator and then reinstall the operator and then it fixed it.

```
{"level":"info","ts":1603819072.647752,"caller":"ops-manager-kubernetes/main.go:167","msg":"Operator environment: prod"}
{"level":"info","ts":1603819072.6477892,"caller":"ops-manager-kubernetes/main.go:168","msg":"Operator version: 1.7.1-51-gcb3282c"}
{"level":"info","ts":1603819072.6477964,"caller":"ops-manager-kubernetes/main.go:169","msg":"Go Version: go1.13.15"}
{"level":"info","ts":1603819072.647802,"caller":"ops-manager-kubernetes/main.go:170","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1603819072.6478136,"caller":"envutil/envutil.go:40","msg":"Environment variables:"}
{"level":"info","ts":1603819072.6478393,"caller":"envutil/envutil.go:46","msg":"BACKUP_WAIT_RETRIES=30"}
{"level":"info","ts":1603819072.6478446,"caller":"envutil/envutil.go:46","msg":"BACKUP_WAIT_SEC=3"}
{"level":"info","ts":1603819072.6478503,"caller":"envutil/envutil.go:46","msg":"KUBERNETES_PORT=tcp://172.30.0.1:443"}
{"level":"info","ts":1603819072.6478548,"caller":"envutil/envutil.go:46","msg":"KUBERNETES_PORT_443_TCP=tcp://172.30.0.1:443"}
{"level":"info","ts":1603819072.6478636,"caller":"envutil/envutil.go:46","msg":"KUBERNETES_PORT_443_TCP_ADDR=172.30.0.1"}
{"level":"info","ts":1603819072.647868,"caller":"envutil/envutil.go:46","msg":"KUBERNETES_PORT_443_TCP_PORT=443"}
{"level":"info","ts":1603819072.6478722,"caller":"envutil/envutil.go:46","msg":"KUBERNETES_PORT_443_TCP_PROTO=tcp"}
{"level":"info","ts":1603819072.647877,"caller":"envutil/envutil.go:46","msg":"KUBERNETES_SERVICE_HOST=172.30.0.1"}
{"level":"info","ts":1603819072.6478834,"caller":"envutil/envutil.go:46","msg":"KUBERNETES_SERVICE_PORT=443"}
{"level":"info","ts":1603819072.647888,"caller":"envutil/envutil.go:46","msg":"KUBERNETES_SERVICE_PORT_HTTPS=443"}
{"level":"info","ts":1603819072.6478925,"caller":"envutil/envutil.go:46","msg":"MANAGED_SECURITY_CONTEXT=true"}
{"level":"info","ts":1603819072.647897,"caller":"envutil/envutil.go:46","msg":"MONGODB_ENTERPRISE_DATABASE_IMAGE=registry.connect.redhat.com/mongodb/enterprise-database"}
{"level":"info","ts":1603819072.6479044,"caller":"envutil/envutil.go:46","msg":"OPERATOR_ENV=prod"}
{"level":"info","ts":1603819072.6479092,"caller":"envutil/envutil.go:46","msg":"OPS_MANAGER_IMAGE_PULL_POLICY=Always"}
{"level":"info","ts":1603819072.647914,"caller":"envutil/envutil.go:46","msg":"OPS_MANAGER_IMAGE_REPOSITORY=registry.connect.redhat.com/mongodb/mongodb-enterprise-ops-manager"}
{"level":"info","ts":1603819072.6479194,"caller":"envutil/envutil.go:46","msg":"WATCH_NAMESPACE="}
{"level":"info","ts":1603819072.647927,"caller":"ops-manager-kubernetes/main.go:79","msg":"Watching namespace "}
{"level":"info","ts":1603819075.0533144,"caller":"ops-manager-kubernetes/main.go:94","msg":"Registering Components."}
{"level":"info","ts":1603819077.4970984,"caller":"operator/mongodbstandalone_controller.go:72","msg":"Registered controller mongodbstandalone-controller"}
{"level":"info","ts":1603819077.4971554,"caller":"operator/mongodbreplicaset_controller.go:214","msg":"Registered controller mongodbreplicaset-controller"}
{"level":"info","ts":1603819077.497175,"caller":"operator/mongodbshardedcluster_controller.go:494","msg":"Registered controller mongodbshardedcluster-controller"}
{"level":"info","ts":1603819077.4972343,"caller":"operator/mongodbuser_controller.go:202","msg":"Registered controller mongodbuser-controller"}
{"level":"info","ts":1603819077.4972606,"caller":"operator/mongodbopsmanager_controller.go:315","msg":"Registered controller opsmanager-controller"}
{"level":"info","ts":1603819077.4972956,"caller":"ops-manager-kubernetes/main.go:110","msg":"Registered CRD: mongodb"}
{"level":"info","ts":1603819077.4973056,"caller":"ops-manager-kubernetes/main.go:110","msg":"Registered CRD: mongodbusers"}
{"level":"info","ts":1603819077.4973109,"caller":"ops-manager-kubernetes/main.go:110","msg":"Registered CRD: opsmanagers"}
{"level":"info","ts":1603819077.4973164,"caller":"ops-manager-kubernetes/main.go:113","msg":"Starting the Cmd."}
{"level":"info","ts":1603819078.3009374,"caller":"agents/upgrade.go:49","msg":"Performing a regular upgrade of Agents for all the MongoDB resources in the cluster..."}
{"level":"warn","ts":1603819078.667917,"caller":"agents/upgrade.go:93","msg":"Failed to schedule Agent upgrade: Status: 403 (Forbidden), ErrorCode: RESOURCE_REQUIRES_WHITELIST, Detail: This resource requires access through a whitelist of ip ranges., this could be due do ongoing Automation Config publishing in Ops Manager and will get fixed during next trial","ShardedCluster":"openshift-operators/my-replica-set-sharded"}
{"level":"info","ts":1603819078.66795,"caller":"agents/upgrade.go:60","msg":"The upgrade of Agents for all the MongoDB resources in the cluster is finished."}
{"level":"info","ts":1603819078.6756887,"caller":"operator/mongodbshardedcluster_controller.go:56","msg":"-> ShardedCluster.Reconcile","ShardedCluster":"openshift-operators/my-replica-set-sharded"}
{"level":"info","ts":1603819078.6757147,"caller":"operator/mongodbshardedcluster_controller.go:57","msg":"ShardedCluster.Spec","ShardedCluster":"openshift-operators/my-replica-set-sharded","spec":{"configSrvPodSpec":{},"mongosPodSpec":{},"shardPodSpec":{},"version":"4.4.0-ent","credentials":"mongodb-opsmanager-creds","opsManager":{"configMapRef":{"name":"mongodb-cloudmanager-orgid"}},"cloudManager":{"configMapRef":{}},"persistent":true,"type":"ShardedCluster","agent":{"startupOptions":null},"members":3,"podSpec":{},"security":{"tls":{"secretRef":{}}},"connectivity":{}}}
{"level":"info","ts":1603819078.6757572,"caller":"operator/mongodbshardedcluster_controller.go:58","msg":"ShardedCluster.Status","ShardedCluster":"openshift-operators/my-replica-set-sharded","status":{"phase":"Reconciling","lastTransition":"2020-10-27T17:17:58Z","version":"","type":""}}
{"level":"info","ts":1603819078.6757817,"caller":"operator/mongodbshardedcluster_controller.go:59","msg":"ShardedClusterScaling","ShardedCluster":"openshift-operators/my-replica-set-sharded","mongosScaler":{"DesiredMembers":0,"CurrentMembers":0},"configSrvScaler":{"DesiredMembers":0,"CurrentMembers":0},"mongodsPerShardScaler":{"DesiredMembers":0,"CurrentMembers":0},"desiredShards":0,"currentShards":0}
{"level":"info","ts":1603819078.6758103,"caller":"operator/mongodbshardedcluster_controller.go:112","msg":"ShardedCluster.doShardedClusterProcessing","ShardedCluster":"openshift-operators/my-replica-set-sharded"}
{"level":"info","ts":1603819078.825625,"caller":"operator/common_controller.go:120","msg":"Using Ops Manager version v20201013","ShardedCluster":"openshift-operators/my-replica-set-sharded"}
{"level":"info","ts":1603819079.0157902,"caller":"operator/kubehelper.go:1040","msg":"secret my-replica-set-sharded-mongos-cert doesn't exist yet","ShardedCluster":"openshift-operators/my-replica-set-sharded"}
{"level":"info","ts":1603819079.015828,"caller":"operator/kubehelper.go:1040","msg":"secret my-replica-set-sharded-config-cert doesn't exist yet","ShardedCluster":"openshift-operators/my-replica-set-sharded"}
E1027 17:17:59.174558       1 runtime.go:78] Observed a panic: runtime.boundsError{x:0, y:0, signed:true, code:0x0} (runtime error: index out of range [0] with length 0)
goroutine 818 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x17138e0, 0xc0021cfba0)
	/data/mci/75efdc2f236077e16f5d3e0d25b23dae/src/github.com/10gen/ops-manager-kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/data/mci/75efdc2f236077e16f5d3e0d25b23dae/src/github.com/10gen/ops-manager-kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x17138e0, 0xc0021cfba0)
	/opt/golang/go1.13/src/runtime/panic.go:679 +0x1b2
github.com/10gen/ops-manager-kubernetes/pkg/controller/operator.(*ReconcileMongoDbShardedCluster).ensureX509InKubernetes(0xc000267d80, 0xc00058b500, 0xc0009231e0, 0xc000923380, 0x2720190, 0x0, 0x0, 0xc008a0e608, 0x0, 0xc008a05980)
	/data/mci/75efdc2f236077e16f5d3e0d25b23dae/src/github.com/10gen/ops-manager-kubernetes/pkg/controller/operator/mongodbshardedcluster_controller.go:201 +0xe74
github.com/10gen/ops-manager-kubernetes/pkg/controller/operator.(*ReconcileMongoDbShardedCluster).doShardedClusterProcessing(0xc000267d80, 0x17f9dc0, 0xc00058b500, 0xc008a0e608, 0x0, 0x0, 0x0, 0xc0008d58c8)
	/data/mci/75efdc2f236077e16f5d3e0d25b23dae/src/github.com/10gen/ops-manager-kubernetes/pkg/controller/operator/mongodbshardedcluster_controller.go:159 +0xde9
github.com/10gen/ops-manager-kubernetes/pkg/controller/operator.(*ReconcileMongoDbShardedCluster).Reconcile(0xc000267d80, 0xc0008f6540, 0x13, 0xc0008f6520, 0x16, 0xc000292000, 0x0, 0x0, 0x0)
	/data/mci/75efdc2f236077e16f5d3e0d25b23dae/src/github.com/10gen/ops-manager-kubernetes/pkg/controller/operator/mongodbshardedcluster_controller.go:61 +0x86d
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00025e9a0, 0x1685fe0, 0xc0002d1980, 0xc00012f500)
	/data/mci/75efdc2f236077e16f5d3e0d25b23dae/src/github.com/10gen/ops-manager-kubernetes/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:246 +0x162
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00025e9a0, 0x0)
	/data/mci/75efdc2f236077e16f5d3e0d25b23dae/src/github.com/10gen/ops-manager-kubernetes/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:222 +0xcb
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc00025e9a0)
	/data/mci/75efdc2f236077e16f5d3e0d25b23dae/src/github.com/10gen/ops-manager-kubernetes/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:201 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000871f30)
	/data/mci/75efdc2f236077e16f5d3e0d25b23dae/src/github.com/10gen/ops-manager-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000871f30, 0x3b9aca00, 0x0, 0x1, 0xc00041a180)
	/data/mci/75efdc2f236077e16f5d3e0d25b23dae/src/github.com/10gen/ops-manager-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc000871f30, 0x3b9aca00, 0xc00041a180)
	/data/mci/75efdc2f236077e16f5d3e0d25b23dae/src/github.com/10gen/ops-manager-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/data/mci/75efdc2f236077e16f5d3e0d25b23dae/src/github.com/10gen/ops-manager-kubernetes/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:183 +0x446
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 818 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/data/mci/75efdc2f236077e16f5d3e0d25b23dae/src/github.com/10gen/ops-manager-kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x105
panic(0x17138e0, 0xc0021cfba0)
	/opt/golang/go1.13/src/runtime/panic.go:679 +0x1b2
github.com/10gen/ops-manager-kubernetes/pkg/controller/operator.(*ReconcileMongoDbShardedCluster).ensureX509InKubernetes(0xc000267d80, 0xc00058b500, 0xc0009231e0, 0xc000923380, 0x2720190, 0x0, 0x0, 0xc008a0e608, 0x0, 0xc008a05980)
	/data/mci/75efdc2f236077e16f5d3e0d25b23dae/src/github.com/10gen/ops-manager-kubernetes/pkg/controller/operator/mongodbshardedcluster_controller.go:201 +0xe74
github.com/10gen/ops-manager-kubernetes/pkg/controller/operator.(*ReconcileMongoDbShardedCluster).doShardedClusterProcessing(0xc000267d80, 0x17f9dc0, 0xc00058b500, 0xc008a0e608, 0x0, 0x0, 0x0, 0xc0008d58c8)
	/data/mci/75efdc2f236077e16f5d3e0d25b23dae/src/github.com/10gen/ops-manager-kubernetes/pkg/controller/operator/mongodbshardedcluster_controller.go:159 +0xde9
github.com/10gen/ops-manager-kubernetes/pkg/controller/operator.(*ReconcileMongoDbShardedCluster).Reconcile(0xc000267d80, 0xc0008f6540, 0x13, 0xc0008f6520, 0x16, 0xc000292000, 0x0, 0x0, 0x0)
	/data/mci/75efdc2f236077e16f5d3e0d25b23dae/src/github.com/10gen/ops-manager-kubernetes/pkg/controller/operator/mongodbshardedcluster_controller.go:61 +0x86d
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00025e9a0, 0x1685fe0, 0xc0002d1980, 0xc00012f500)
	/data/mci/75efdc2f236077e16f5d3e0d25b23dae/src/github.com/10gen/ops-manager-kubernetes/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:246 +0x162
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00025e9a0, 0x0)
	/data/mci/75efdc2f236077e16f5d3e0d25b23dae/src/github.com/10gen/ops-manager-kubernetes/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:222 +0xcb
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc00025e9a0)
	/data/mci/75efdc2f236077e16f5d3e0d25b23dae/src/github.com/10gen/ops-manager-kubernetes/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:201 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000871f30)
	/data/mci/75efdc2f236077e16f5d3e0d25b23dae/src/github.com/10gen/ops-manager-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000871f30, 0x3b9aca00, 0x0, 0x1, 0xc00041a180)
	/data/mci/75efdc2f236077e16f5d3e0d25b23dae/src/github.com/10gen/ops-manager-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc000871f30, 0x3b9aca00, 0xc00041a180)
	/data/mci/75efdc2f236077e16f5d3e0d25b23dae/src/github.com/10gen/ops-manager-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/data/mci/75efdc2f236077e16f5d3e0d25b23dae/src/github.com/10gen/ops-manager-kubernetes/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:183 +0x446
```

**Comment by soulaw-mkii** [comment]
I had the same experience. Whenever I deleted my om resource, either I enter an infinite restart loop or the monitoring agent will not run properly across the appdb pods when I apply them back.

**Comment by alberttwong** [comment]
Do you have any logs to share?

**Comment by jamesbroadhead** [comment]
In order to help us manage issues and requests we have switched from GitHub Issues to the [MongoDB Support Center](https://support.mongodb.com/). Please use your Enterprise support account to raise your requests. 

If this issue is still affecting you, please open a [Support Case](https://support.mongodb.com/) or for non-blocking issues, you can make a [Feature Request](https://feedback.mongodb.com/forums/924355-ops-tools)
