### ISSUE TITLE
Ops Manager cannot connect to the database

### ISSUE THREAD

**Issue by uroot666** [mongodb/mongodb-enterprise-kubernetes#62]
`2020-01-15T02:03:44.157+0000 [main] WARN  com.xgen.svc.core.AppSettings [AppSettings.java.run:508] - Failed to refresh database properties
com.mongodb.MongoTimeoutException: Timed out after 20000 ms while waiting for a server that matches com.mongodb.Mongo$4@47547132. Client view of cluster state is {type=REPLICA_SET, servers=[{address=ops-manager-db-1.ops-manager-db-svc.mongodb.svc.cluster.local:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='mongodb-ops-manager', source='admin', password=<hidden>, mechanismProperties={}}}, caused by {com.mongodb.MongoCommandException: Command failed with error 18: 'Authentication failed.' on server ops-manager-db-1.ops-manager-db-svc.mongodb.svc.cluster.local:27017. The full response is { "ok" : 0.0, "errmsg" : "Authentication failed.", "code" : 18, "codeName" : "AuthenticationFailed" }}}, {address=ops-manager-db-2.ops-manager-db-svc.mongodb.svc.cluster.local:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}, {address=ops-manager-db-0.ops-manager-db-svc.mongodb.svc.cluster.local:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]
	at com.mongodb.connection.BaseCluster.createTimeoutException(BaseCluster.java:389)
	at com.mongodb.connection.BaseCluster.selectServer(BaseCluster.java:108)
	at com.mongodb.Mongo.getConnectedClusterDescription(Mongo.java:887)
	at com.mongodb.Mongo.createClientSession(Mongo.java:877)
	at com.mongodb.Mongo$3.getClientSession(Mongo.java:866)
	at com.mongodb.Mongo$3.execute(Mongo.java:823)
	at com.mongodb.Mongo$3.execute(Mongo.java:813)
	at com.mongodb.DBCursor.initializeCursor(DBCursor.java:877)
	at com.mongodb.DBCursor.hasNext(DBCursor.java:144)
	at com.xgen.svc.core.dao.system.AppPropertyDao.getValues(AppPropertyDao.java:41)
	at com.xgen.svc.core.AppSettings.getDBProperties(AppSettings.java:525)
	at com.xgen.svc.core.AppSettings$DatabasePropertiesRefresher.run(AppSettings.java:500)
	at com.xgen.svc.core.AppSettings.refreshDatabaseCache(AppSettings.java:755)
	at com.xgen.svc.core.AppSettings.<init>(AppSettings.java:293)
	at com.xgen.svc.core.AppSettings.<init>(AppSettings.java:226)
	at com.xgen.svc.core.PreFlightCheck$1.configure(PreFlightCheck.java:245)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:61)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:344)
	at com.google.inject.spi.Elements.getElements(Elements.java:103)
	at com.mycila.inject.jsr250.Jsr250.hasJSR250Module(Jsr250.java:85)
	at com.mycila.inject.jsr250.Jsr250.createInjector(Jsr250.java:73)
	at com.mycila.inject.jsr250.Jsr250.createInjector(Jsr250.java:47)
	at com.mycila.inject.jsr250.Jsr250.createInjector(Jsr250.java:43)
	at com.xgen.svc.core.PreFlightCheck.<init>(PreFlightCheck.java:89)
	at com.xgen.svc.mms.MmsPreFlightCheck.<init>(MmsPreFlightCheck.java:68)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.xgen.svc.core.PreFlightCheck.main(PreFlightCheck.java:205)`

**Comment by antonlisovenko** [comment]
Hi @uroot666 
Can you give more information please? What are you doing (creating/updating OM), which version of the Operator, what is the configuration file for MongoDBOpsManager resource?

**Comment by antonlisovenko** [comment]
Closing this, @uroot666 feel free to reopen if it's still the problem

**Comment by jintoppy** [comment]
I am getting the same error. 

**Ops Manager version: 4.2.15**

**Kubernetes version**

Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.12-gke.2", GitCommit:"fb7add51f767aae42655d39972210dc1c5dbd4b3", GitTreeState:"clean", BuildDate:"2020-06-01T22:20:10Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}

I am following this [tutorial](https://www.mongodb.com/blog/post/running-mongodb-ops-manager-in-kubernetes). 

I was able to run the same command successfully last month. But, now it is giving this error. 

kubectl apply -f ops-manager.yaml

```
2020-08-30T16:53:49.961+0000 [main] WARN  com.xgen.svc.core.AppSettings [AppSettings.java.run:510] - Failed to refresh database properties
com.mongodb.MongoTimeoutException: Timed out after 20000 ms while waiting for a server that matches com.mongodb.Mongo$4@33f98231. Client view of cluster state is {type=REPLICA_SET, servers=[{address=ops-manager-db-1.ops-manager-db-svc.mongodb.svc.cluster.local:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: connect timed out}}, {address=ops-manager-db-2.ops-manager-db-svc.mongodb.svc.cluster.local:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketException: ops-manager-db-2.ops-manager-db-svc.mongodb.svc.cluster.local: Temporary failure in name resolution}, caused by {java.net.UnknownHostException: ops-manager-db-2.ops-manager-db-svc.mongodb.svc.cluster.local: Temporary failure in name resolution}}, {address=ops-manager-db-0.ops-manager-db-svc.mongodb.svc.cluster.local:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]
	at com.mongodb.connection.BaseCluster.createTimeoutException(BaseCluster.java:389)
	at com.mongodb.connection.BaseCluster.selectServer(BaseCluster.java:108)
	at com.mongodb.Mongo.getConnectedClusterDescription(Mongo.java:887)
	at com.mongodb.Mongo.createClientSession(Mongo.java:877)
	at com.mongodb.Mongo$3.getClientSession(Mongo.java:866)
	at com.mongodb.Mongo$3.execute(Mongo.java:823)
	at com.mongodb.Mongo$3.execute(Mongo.java:813)
	at com.mongodb.DBCursor.initializeCursor(DBCursor.java:877)
	at com.mongodb.DBCursor.hasNext(DBCursor.java:144)
	at com.xgen.svc.core.dao.system.AppPropertyDao.getValues(AppPropertyDao.java:41)
	at com.xgen.svc.core.AppSettings.getDBProperties(AppSettings.java:527)
	at com.xgen.svc.core.AppSettings$DatabasePropertiesRefresher.run(AppSettings.java:502)
	at com.xgen.svc.core.AppSettings.refreshDatabaseCache(AppSettings.java:757)
	at com.xgen.svc.core.AppSettings.<init>(AppSettings.java:295)
	at com.xgen.svc.core.AppSettings.<init>(AppSettings.java:228)
	at com.xgen.svc.core.PreFlightCheck$1.configure(PreFlightCheck.java:244)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:61)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:344)
	at com.google.inject.spi.Elements.getElements(Elements.java:103)
	at com.mycila.inject.jsr250.Jsr250.hasJSR250Module(Jsr250.java:85)
	at com.mycila.inject.jsr250.Jsr250.createInjector(Jsr250.java:73)
	at com.mycila.inject.jsr250.Jsr250.createInjector(Jsr250.java:47)
	at com.mycila.inject.jsr250.Jsr250.createInjector(Jsr250.java:43)
	at com.xgen.svc.core.PreFlightCheck.<init>(PreFlightCheck.java:88)
	at com.xgen.svc.mms.MmsPreFlightCheck.<init>(MmsPreFlightCheck.java:68)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.xgen.svc.core.PreFlightCheck.main(PreFlightCheck.java:204)
```

<img width="731" alt="Screenshot 2020-08-30 at 10 32 19 PM" src="https://user-images.githubusercontent.com/3390198/91665079-c0827280-eb10-11ea-99b8-e687422ff482.png">
